# Generated by Django 5.2 on 2025-04-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_title'),
        ('subdread', '0012_flair_created_on_flair_updated_on_rule_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='subdread.flair'),
        ),
    ]
