# Generated by Django 5.1 on 2025-02-26 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subdread',
            name='users',
            field=models.ManyToManyField(related_name='subdreads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Flair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subdread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flairs', to='subdread.subdread')),
            ],
            options={
                'db_table': 'flair',
            },
        ),
    ]
