# Generated by Django 5.1 on 2025-03-09 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0003_subdread_users_flair'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subdread',
            name='moderators',
            field=models.ManyToManyField(related_name='moderated_subdreads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='flair',
            unique_together={('name', 'subdread')},
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='subdread.categories')),
            ],
        ),
        migrations.AddField(
            model_name='subdread',
            name='categories',
            field=models.ManyToManyField(related_name='subdreads', to='subdread.categories'),
        ),
    ]
