# Generated by Django 5.1 on 2025-03-09 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0004_subdread_moderators_alter_flair_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
