# Generated by Django 5.1 on 2025-03-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0006_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdread',
            name='adults_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subdread',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AddField(
            model_name='subdread',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='subdread',
            name='type',
            field=models.CharField(choices=[('0', 'Private'), ('1', 'Public')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
