# Generated by Django 5.2 on 2025-04-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0008_alter_subdread_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdread',
            name='banner',
            field=models.ImageField(blank=True, default='/banner/default_banner.png', upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='subdread',
            name='icon',
            field=models.ImageField(blank=True, default='/icon/default_icon.png', upload_to='icon'),
        ),
    ]
