# Generated by Django 5.1 on 2025-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0008_alter_subdread_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdread',
            name='banner',
            field=models.ImageField(blank=True, default='/static/images/default_banner.png', null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='subdread',
            name='icon',
            field=models.ImageField(blank=True, default='/static/images/default_icon.png', null=True, upload_to='icon'),
        ),
    ]
