# Generated by Django 5.2 on 2025-04-06 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subdread', '0010_alter_subdread_banner_alter_subdread_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('subdread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='subdread.subdread')),
            ],
            options={
                'db_table': 'rules',
                'unique_together': {('name', 'subdread')},
            },
        ),
    ]
