# Generated by Django 5.2 on 2025-04-20 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chatted_with',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
